import json
from pathlib import Path
from typing import Dict, List, Optional, Iterator
from PIL import Image
import torch
from torch.utils.data import Dataset, DataLoader
import torchvision.transforms as transforms


class CLEVRDataset(Dataset):
    """
    CLEVR dataset using processed JSONL files.
    Works with train/val splits generated by CLEVRProcessor.
    """

    def __init__(self, processed_dir: str, split: str = "train",
        image_root: Optional[str] = None, image_size: tuple[int, int] = (320, 240),
        max_samples: Optional[int] = None):
        self.split = split
        self.processed_dir = Path(processed_dir)
        self.image_root = Path(image_root) if image_root else None
        self.image_size = image_size

        # Load processed JSONL
        questions_file = self.processed_dir / f"processed_{split}_questions.jsonl"
        scenes_file = self.processed_dir / f"processed_{split}_scenes.jsonl"

        print(f"Loading processed questions from {questions_file}...")
        self.questions = list(self._load_jsonl(questions_file))
        if max_samples:
            self.questions = self.questions[:max_samples]

        # Load scenes mapping
        print(f"Loading processed scenes from {scenes_file}...")
        self.scenes = {entry['image_id']: entry for entry in self._load_jsonl(scenes_file)}

        # Build answer vocabulary
        self.answer_vocab = self._build_answer_vocab()
        self.answer_to_idx = {ans: idx for idx, ans in enumerate(self.answer_vocab)}
        self.idx_to_answer = {idx: ans for ans, idx in self.answer_to_idx.items()}

        print(f"Loaded {len(self.questions)} questions for '{split}' split")
        print(f"Answer vocabulary size: {len(self.answer_vocab)}")

    def _load_jsonl(self, path: Path) -> Iterator[Dict]:
        if not path.exists():
            raise FileNotFoundError(f"Processed file not found: {path}")
        with path.open("r") as f:
            for line in f:
                yield json.loads(line)

    def _build_answer_vocab(self) -> List[str]:
        answers = set()
        for q in self.questions:
            if "answer" in q:
                answers.add(q["answer"])
        return sorted(answers)

    def __len__(self) -> int:
        return len(self.questions)

    def __getitem__(self, idx: int) -> Dict:
        q = self.questions[idx]
        item = {
            "question": q["question"],
            "answer": q.get("answer"),
            "answer_idx": self.answer_to_idx[q["answer"]] if "answer" in q else None,
            "program": q.get("program"),
        }

        # Attach scene graph
        item["scene"] = self.scenes.get(q["image_id"], None)
        item["image_id"] = q["image_id"]

        # Load image if image_root provided
        if self.image_root:
            img_path = self.image_root / f"{q['image_id']:06d}.png"
            image = Image.open(img_path).convert("RGB")
            if image.size != self.image_size[::-1]:
                image = image.resize(self.image_size[::-1], Image.BILINEAR)
            item["image"] = image

        return item

    def get_object_attributes(self) -> Dict[str, List[str]]:
        # Get all object attributes from scenes
        attributes = {"colors": set(), "shapes": set(), "materials": set(), "sizes": set()}
        for scene in self.scenes.values():
            for obj in scene["objects"]:
                attributes["colors"].add(obj["color"])
                attributes["shapes"].add(obj["shape"])
                attributes["materials"].add(obj["material"])
                attributes["sizes"].add(obj["size"])
        return {k: sorted(list(v)) for k, v in attributes.items()}


def collateFunc(batch: List[Dict]) -> Dict:
    # Collate function for CLEVR dataset. Converts images to tensors if present.
    if "image" in batch[0]:
        transform = transforms.Compose([
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.485,0.456,0.406], std=[0.229,0.224,0.225])
        ])
        images = torch.stack([transform(item["image"]) for item in batch])
    else:
        images = None

    questions = [item["question"] for item in batch]
    answers = [item["answer"] for item in batch if item.get("answer") is not None]
    answer_indices = torch.tensor([item["answer_idx"] for item in batch if item.get("answer_idx") is not None]) \
        if answers else None

    image_ids = [item["image_id"] for item in batch]

    collated = {
        "images": images,
        "questions": questions,
        "answers": answers if answers else None,
        "answer_indices": answer_indices,
        "image_ids": image_ids
    }
    return collated


def clevrDataloader(processed_dir: str, split: str = "train", batch_size: int = 32,
                    shuffle: bool = True, num_workers: int = 4, image_root: Optional[str] = None,
                    max_samples: Optional[int] = None ) -> DataLoader:
    dataset = CLEVRDataset(processed_dir=processed_dir, split=split, image_root=image_root,
                    max_samples=max_samples)
    return DataLoader(dataset, batch_size=batch_size, shuffle=shuffle, num_workers=num_workers,
                    collate_fn=collateFunc, pin_memory=True)

# Main func 
if __name__ == "__main__":
    PROCESSED_DIR = Path("data/processed")
    dataset = CLEVRDataset(PROCESSED_DIR, split="val", max_samples=100)
    print(f"Dataset size: {len(dataset)}")
    print(f"Answer vocab: {dataset.answer_vocab[:10]}")

    dataloader = clevrDataloader(PROCESSED_DIR, split="val", batch_size=4, num_workers=0)
    batch = next(iter(dataloader))
    print(f"Batch keys: {batch.keys()}")
    if batch["images"] is not None:
        print(f"Batch images shape: {batch['images'].shape}")
    print(f"Sample question: {batch['questions'][0]}")
    print(f"Sample answer: {batch['answers'][0] if batch['answers'] else 'N/A'}")